# Travis configuration file based on https://docs.travis-ci.com/user/languages/python/
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install numpy scipy pandas cython coverage coveralls
  - pip install -r requirements.txt
script:
  - python setup.py test
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coveralls || echo "failed"; fi
#cache:
#  - apt
#sudo: required
